Feature footer
SlipuyKamiN/drink-master-app-frontend pull request #17
Opened 2023-08-28 18:41 UTC by TarasDer

Лишилось додати логіку на кнопку та позиціонування на таблетці

2023-08-29 23:25 UTC, SlipuyKamiN requested changes

2023-08-29 23:25 UTC, SlipuyKamiN commented on src/components/Footer/Nav.jsx
> +  <Link to="/drinks/:categoryName">Drinks</Link>
/drinks/allCategories

2023-08-29 23:25 UTC, SlipuyKamiN commented on src/components/Footer/SubscribeForm.module.scss
> +  font-family: Manrope;
font-family вже вказаний в боді

2023-08-29 23:25 UTC, SlipuyKamiN commented on src/components/Footer/SubscribeForm.module.scss
> +  color: #f3f3f3;
Використай глобальну змінну з палітри

2023-08-29 23:25 UTC, SlipuyKamiN commented on src/components/Footer/Nav.module.scss
> +  color: #f3f3f3;
Використай змінну з глобальної палітри

2023-08-29 23:25 UTC, SlipuyKamiN commented on src/components/Footer/SubscribeForm.module.scss
> +  color: rgb(243, 243, 243);
Всі кольори з глобальних змінних

2023-09-01 19:29 UTC, SlipuyKamiN requested changes

2023-09-01 19:29 UTC, SlipuyKamiN commented on src/components/Footer/SubscribeForm.module.scss
> +
:placeholder - треба колір по макету прописати

2023-09-01 19:29 UTC, SlipuyKamiN commented on src/components/Footer/Footer.module.scss
> +  padding-bottom: 18px;
цей падінг має бути на <footer

2023-09-01 19:29 UTC, SlipuyKamiN commented on src/components/Footer/Nav.module.scss
> +  font-weight: 500;
font-size: 14px

2023-09-01 19:29 UTC, SlipuyKamiN commented on src/components/Footer/SubscribeForm.module.scss
> +  .errorText {
вийми errorText з цієї області видимості, бо стилі не приїхали для нього

2023-09-01 20:03 UTC, TarasDer commented on src/components/Footer/SubscribeForm.module.scss
> +
Зробив

2023-09-01 20:03 UTC, TarasDer commented on src/components/Footer/Footer.module.scss
> +  padding-bottom: 18px;
Зробив

2023-09-01 20:03 UTC, TarasDer commented on src/components/Footer/Nav.module.scss
> +  font-weight: 500;
тут же 14px з body забираються

2023-09-01 20:03 UTC, TarasDer commented on src/components/Footer/SubscribeForm.module.scss
> +  .errorText {
Зробив

2023-09-01 21:02 UTC, SlipuyKamiN approved these changes

2023-09-01 21:02 UTC, merged