Feature main page
SlipuyKamiN/drink-master-app-frontend pull request #18
Opened 2023-08-29 14:01 UTC by VitekVP

2023-08-29 23:11 UTC, SlipuyKamiN requested changes

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/Shared/DrinkCard.jsx
> +    <div className={sass.card}>
замість div - тег li

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/MainPage/PreviewDrinks.jsx
> +                        <li>
звідси li прибирай, перенеси в картку, замість div,

key - повинен бути на найвищому компоненті всередині map, так як ти в списку вище зробив, тому в тебе і помилка в консолі. Просто прибери цей li, а в картку постав замість div і все буде ок

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/Shared/DrinkCard.module.scss
> +  width: 360px;
max-width: 360px
замість width. Бо на ширині екрану 320 - вилазять картки

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/Shared/DrinkCard.module.scss
> +    width: 342px;
А тут просто дописуєш max-width: none;

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/MainPage/PreviewDrinks.jsx
> +      {isLoading && <LoadingSpinner />}
Це безкорисно, бо в тебе вже є if вище 30 - 31 рядок

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/MainPage/PreviewDrinks.jsx
> +      <section className={sass.drinks}>
Всередину секції ставиш контейнер

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/pages/MainPage.jsx
> +      </Container>
А звідси - цей контейнер забираєш

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/MainPage/PreviewDrinks.module.scss
> +
в його лішок ul > li на першій вкладеності. Між ними на таблетці має бути відстань 80рх, в тебе вийшло 60 рх і то, через падінги. Падінгами дітей робити відступи між батьками - не дуже добре, тому треба для лішок категорій зробити маржин нижній, окрім останнього

2023-08-29 23:11 UTC, SlipuyKamiN commented on src/components/MainPage/PreviewDrinks.module.scss
> +  &:hover {
стан фокус теж додай

2023-08-30 13:43 UTC, VitekVP commented on src/components/MainPage/PreviewDrinks.module.scss
> +  &:hover {
ok

2023-08-30 13:48 UTC, VitekVP commented on src/components/MainPage/PreviewDrinks.jsx
> +      {isLoading && <LoadingSpinner />}
ok

2023-08-30 13:55 UTC, VitekVP commented on src/components/MainPage/PreviewDrinks.jsx
> +      <section className={sass.drinks}>
ok

2023-08-30 13:55 UTC, VitekVP commented on src/pages/MainPage.jsx
> +      </Container>
ok

2023-08-30 14:01 UTC, VitekVP commented on src/components/Shared/DrinkCard.jsx
> +    <div className={sass.card}>
ok

2023-08-30 14:01 UTC, VitekVP commented on src/components/MainPage/PreviewDrinks.jsx
> +                        <li>
ok

2023-08-30 14:09 UTC, VitekVP commented on src/components/Shared/DrinkCard.module.scss
> +  width: 360px;
ok

2023-08-30 14:09 UTC, VitekVP commented on src/components/Shared/DrinkCard.module.scss
> +    width: 342px;
ok

2023-08-30 15:55 UTC, VitekVP commented on src/components/MainPage/PreviewDrinks.module.scss
> +
ок. виправив. довелося пофіксити геометрію усіх суміжних елементів

2023-08-30 16:21 UTC, SlipuyKamiN approved these changes

2023-08-30 16:21 UTC, merged