Feature/favorite
SlipuyKamiN/drink-master-app-frontend pull request #19
Opened 2023-08-29 17:31 UTC by Bad-Raider

2023-08-29 23:32 UTC, SlipuyKamiN requested changes

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    color: #f3f3f3;
Використай кольори з глобальних стилів

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +        background-color: #434D67;
Тут теж кольори і transition є в глобальних стилях

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    &:hover{
додай focus

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.jsx
> +  };
для RTK Query тобі вже не потрібні try...catch і async await, ти просто викликаєш свій dispatch в потрібному місці

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.jsx
> +  return <>
обгортка <></> безкорисна, в тебе є li

2023-08-29 23:32 UTC, SlipuyKamiN commented on src/pages/FavoritePage.jsx
> +      {isError && <div>Ooooopsss!!!!</div>}
Не знаю нічо про це.

Маєш функцію notification для обробки помилок

2023-09-01 18:01 UTC, SlipuyKamiN requested changes

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.jsx
> +              rel="noreferrer"
target, rel - тут лишнє. Нам не треба, щоб це відкривалось у новій вкладці

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/pages/FavoritePage.jsx
> +  console.log("data", data.totalHits);
вже не треба

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    width: 335px;
max-width: 335px

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +        width: 342px;
max-width: none

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    opacity: 0.5;
color: rgba($color: #ХХХХХХ $alpha: 0.5)

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.jsx
> +          <p className={scss.RecipesItemText}>{description || 'descr'}</p>
Рендер по умові
{description && <p description}

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    margin-top: 18px;
перенеси на subtitle - margin-bottom. Якщо вже почав зверху вниз всім нижні маржини, то так і притримуйся

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    margin-left: 8px;
Не треба margin. Якщо в батьківському флекс, то прийнято ставити gap і норм

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    border-radius: 50px;
font-weight: 600, по макету

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    display: flex;
gap, щоб між кнопками була відстань

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    transition: color 250ms linear;
font-size, font-weight

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    transition: color 250ms linear;
transition: background-color, і для часу і типу, використай змінну з глобальних змінних

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesList.jsx
> +    <section className={scss.ContainerRecipesList}>
це повністю прибираєш звідси.

в FavoritePage, огортаєш все в секцію з падінгами верхнім і нижнім, а потім всередині все обгортаєш в компонент <Container, з Shared

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/pages/FavoritePage.jsx
> +        <>
Тут "<"section">"<"Container">"...

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +    margin-bottom: 40px;
Це забудь. Цю роботу має робити padding на самій батьківській секції

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/pages/FavoritePage.jsx
> +        <>
PageTitle не забув?

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +    opacity: 0.5;
line-height

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +
height: 360px

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +
desktop: 400x400

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.jsx
> +          <h4 className={scss.RecipesItemSubTitle}>ingridients</h4>
З великої букви

2023-09-01 18:01 UTC, SlipuyKamiN commented on src/components/FavoritePage/RecipesItem.module.scss
> +
background-color: додай, такий як у Віктора на mainPage

2023-09-01 19:42 UTC, Bad-Raider commented on src/components/FavoritePage/RecipesItem.jsx
> +          <p className={scss.RecipesItemText}>{description || 'descr'}</p>
У такому випадку елемент, де немає опису буде меншого розміру, ніж інші у сітці, пропоную такий варіант:

          <p className={scss.RecipesItemText}>{description || 'description is absent'}</p>

2023-09-02 00:00 UTC, SlipuyKamiN approved these changes

2023-09-02 00:00 UTC, merged