Feature/drink page
SlipuyKamiN/drink-master-app-frontend pull request #41
Opened 2023-09-02 22:01 UTC by Andrii-Sh

DrikPage done. Please check/

2023-09-02 22:34 UTC, SlipuyKamiN requested changes

2023-09-02 22:34 UTC, SlipuyKamiN commented on src/components/DrinksPage/DrinksList.jsx
> +              id={item._id.$oid}
кривий id передаєш

2023-09-02 22:34 UTC, SlipuyKamiN commented on src/components/DrinksPage/DrinksList.jsx
> +    <div>
цей дів безкорисний

2023-09-02 22:34 UTC, SlipuyKamiN commented on src/components/DrinksPage/DrinksList.module.scss
> +        margin-bottom: 20px;
маржином дитини відсуваєш сусіда батька. Просто той div забереш

2023-09-02 22:34 UTC, SlipuyKamiN commented on src/components/FavoritePage/Paginator.module.scss
> +        margin-bottom: 140px;
ці маржини - це мають бути падінги на секції найвищій

2023-09-02 22:34 UTC, SlipuyKamiN commented on src/components/DrinksPage/DrinksSearch.jsx
> +        defaultValue=""
при перезагрузці сторінки, коли в адресній строці є параметри - інпути всеодно пусті. Треба поправити, щоб дані бралися з адресної строки, а якщо їх там нема, то пусті.

2023-09-03 08:12 UTC, Andrii-Sh commented on src/components/DrinksPage/DrinksList.jsx
> +              id={item._id.$oid}
done

2023-09-03 08:13 UTC, Andrii-Sh commented on src/components/DrinksPage/DrinksList.jsx
> +    <div>
done

2023-09-03 08:14 UTC, Andrii-Sh commented on src/components/DrinksPage/DrinksList.module.scss
> +        margin-bottom: 20px;
done

2023-09-03 08:45 UTC, Andrii-Sh commented on src/components/FavoritePage/Paginator.module.scss
> +        margin-bottom: 140px;
done

2023-09-03 12:33 UTC, SlipuyKamiN approved these changes

2023-09-03 12:34 UTC, merged