Features/header
SlipuyKamiN/drink-master-app-frontend pull request #42
Opened 2023-09-02 22:33 UTC by alex-k22

1st PR

2023-09-02 23:32 UTC, SlipuyKamiN requested changes

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +  margin-top: 160px;
padding

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +  height: 39px;
не працює, бо display: inline

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +  border: 1px solid rgba(243, 243, 243, 0.2);
rgba($color:  $variable-name $alpha: 0.2)

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +@import '../../index.scss';
тобі не треба всі стилі, а тільки vars

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Header.module.scss
> +@import '../../index.scss';
Тобі не треба всі стилі, а тільки vars

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +  gap: 32px;
виправиш display посиланням і gap буде менший

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Header.module.scss
> +  transition: transform $transition-duration;
треба продумати скрол, бо на малому екрані не все влазить

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Header.module.scss
> +  background-color: $main-bg-color;
має бути фон з шаріками

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Header.module.scss
> +  transform: translateY(0%);
Якщо дроп меню не закрити і розширити екран, то воно так і лишиться відкрите

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/UserInfoModal.module.scss
> +  opacity: 0;
cursor: pointer

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/UserInfoModal.module.scss
> +  background-color: $primary-white-color;
transition

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/UserInfoModal.jsx
> +          {isLoading ? <LoadingSpinner size={44} /> : 'Save changes'}
спінер випадає за межі кнопки

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Logo.module.scss
>          line-height: 1.22;
margin-left на таблетці теж замінити на gap

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.jsx
> +            to="/main"
to="/"

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Header.module.scss
> +  border-bottom: 1px solid rgba(243, 243, 243, 0.2);
rgba($color: $var-name $alpha: 0.2)

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.jsx
> +            className={({ isActive }) => `${isActive ? css.active : css.link}`}
NavLink автоматично ставить клас active, тобі в scss треба буде прописати не просто .active, а всередині link, &.active

2023-09-02 23:32 UTC, SlipuyKamiN commented on src/components/Header/Navigation.module.scss
> +  :focus {
& пропустив

2023-09-03 05:29 UTC, alex-k22 commented on src/components/Header/Navigation.module.scss
> +  border: 1px solid rgba(243, 243, 243, 0.2);
У нас в переменных нет такого цвета

2023-09-03 06:21 UTC, alex-k22 commented on src/components/Header/Navigation.jsx
> +            className={({ isActive }) => `${isActive ? css.active : css.link}`}
У меня так не работает. Возможно, из-за того, что компилятор к названиям классов в module.css добавляет случайные приставки. А с отдельным классом .active работает

2023-09-03 12:48 UTC, SlipuyKamiN approved these changes

2023-09-03 12:48 UTC, merged