Feature motivation
SlipuyKamiN/drink-master-app-frontend pull request #59
Opened 2023-09-04 17:19 UTC by VitekVP

2023-09-04 21:13 UTC, SlipuyKamiN requested changes

2023-09-04 21:13 UTC, SlipuyKamiN commented on src/components/Shared/MotivatingModal.module.scss
> +  margin: 0 auto 20px;
кнопка завжди на різній висоті, залежно від контенту. Ти можеш для контенту задати фіксовану висоту, тоді кнопка стане на місце, як по макету

2023-09-04 21:13 UTC, SlipuyKamiN commented on src/components/Shared/MotivatingModal.module.scss
> +  max-width: 239px;
Ширину фіксуй падінгами батька

2023-09-04 21:13 UTC, SlipuyKamiN commented on src/components/Shared/MotivatingModal.module.scss
> +.wrapperThree {
В тебе три врапери з мінімальними змінами, треба зробити щоб був основний один клас, а інші наслідувати і тільки щось своє дописували.

Як варіант https://sass-lang.com/documentation/at-rules/extend/

2023-09-05 20:17 UTC, VitekVP commented on src/components/Shared/MotivatingModal.module.scss
> +  margin: 0 auto 20px;
переробив трохи по іншому, оскільки пофіксив що текстова частина різна, тому її прив'язав до гори а кнопку до низу

2023-09-05 21:01 UTC, VitekVP commented on src/components/Shared/MotivatingModal.module.scss
> +  max-width: 239px;
теж повязано з попереднім зауваженням. але я потестив і мені здається що так буде оптимально

2023-09-06 05:34 UTC, VitekVP commented on src/components/Shared/MotivatingModal.module.scss
> +.wrapperThree {
ok

2023-09-06 17:41 UTC, SlipuyKamiN approved these changes

2023-09-06 17:41 UTC, merged